version: "3"

dotenv: [".env"]

tasks:
  run:
    desc: Run python program. It will also start up the database.
    deps: [database-up]
    cmd: fastapi dev main.py --host $SERVER_HOST --port $SERVER_PORT

  container-run:
    desc: Run application in the docker or podman container. It will also start up the database.
    deps: [database-up, generate-requirements]
    dir: "{{.USER_WORKING_DIR}}/containers"
    aliases: [crun]
    cmd: bash -c "$RUNNER-compose -f service.yml up -d --no-deps --build"

  container-stop:
    desc: Stop docker or podman container with running application.
    dir: "{{.USER_WORKING_DIR}}/containers"
    aliases: [cstop]
    cmd: bash -c "$RUNNER-compose -f service.yml down"

  database-up:
    desc: Create the database container throw docker or podman.
    dir: "{{.USER_WORKING_DIR}}/containers"
    aliases: [db]
    cmd: bash -c "$RUNNER-compose -f database.yml up -d"

  database-down:
    desc: Drop the database container throw docker or podman.
    dir: "{{.USER_WORKING_DIR}}/containers"
    aliases: [dbd]
    cmd: bash -c "$RUNNER-compose -f database.yml down"

  migrate:
    desc: Installs and runs alembic migrations engine
    deps: [database-up]
    aliases: [m, mg]
    cmds:
      - pip install alembic
      - alembic upgrade head

  lint:
    desc: Installs and runs ruff linter
    cmds:
      - pip install ruff
      - ruff check

  format:
    desc: Auto formatting python code with ruff
    aliases: [f, fmt]
    cmds:
      - pip install ruff
      - ruff format

  test:
    desc: Run all tests
    cmds:
      - python -m unittest discover

  generate-requirements:
    desc: Generate requirements.txt file for Docker containers
    aliases: [req]
    cmd: pip freeze > requirements.txt
