# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quotes.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cquotes.proto" \n\rUserIDRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t":\n\x15UserAndQuoteIDRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08quote_id\x18\x02 \x01(\t"\x07\n\x05\x45mpty"O\n\x05Quote\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05quote\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\r\n\x05likes\x18\x05 \x01(\x03\x32\xc3\x01\n\x06Quotes\x12\x1d\n\tHeartbeat\x12\x06.Empty\x1a\x06.Empty"\x00\x12+\n\x0fGetQuoteHandler\x12\x0e.UserIDRequest\x1a\x06.Quote"\x00\x12\x37\n\x13GetSameQuoteHandler\x12\x16.UserAndQuoteIDRequest\x1a\x06.Quote"\x00\x12\x34\n\x10LikeQuoteHandler\x12\x16.UserAndQuoteIDRequest\x1a\x06.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "quotes_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USERIDREQUEST"]._serialized_start = 16
    _globals["_USERIDREQUEST"]._serialized_end = 48
    _globals["_USERANDQUOTEIDREQUEST"]._serialized_start = 50
    _globals["_USERANDQUOTEIDREQUEST"]._serialized_end = 108
    _globals["_EMPTY"]._serialized_start = 110
    _globals["_EMPTY"]._serialized_end = 117
    _globals["_QUOTE"]._serialized_start = 119
    _globals["_QUOTE"]._serialized_end = 198
    _globals["_QUOTES"]._serialized_start = 201
    _globals["_QUOTES"]._serialized_end = 396
# @@protoc_insertion_point(module_scope)
