users: {
  shape: person
  style.multiple: true
}

database: Postgres {
  shape: cylinder
  style.multiple: true
}

random_quotes: Random Quotes Site {
  shape: cloud
  link: https://api.quotable.io/random
}

app: {
  servers: {
    fastapi: {
      http
      graphql
    }

    flask: {
      http
      graphql
    }

    litestar: {
      http
      graphql
    }

    starlette: {
      http
      graphql
    }

    grpc
  }

  services: {
    heartbeat_service: Heartbeat Service
    quotes_service: Quotes Service
    quotes_api_service: Quotes Api Service

    quotes_service -> quotes_api_service
  }

  repository: Repository {
    peewee
    sqlalchemy
  }

  servers.fastapi.http -> services.quotes_service
  servers.fastapi.graphql -> services.quotes_service
  servers.flask.http -> services.quotes_service
  servers.flask.graphql -> services.quotes_service
  servers.litestar.http -> services.quotes_service
  servers.litestar.graphql -> services.quotes_service
  servers.starlette.http -> services.quotes_service
  servers.starlette.graphql -> services.quotes_service
  servers.grpc -> services.quotes_service

  servers.fastapi.http -> services.heartbeat_service
  servers.fastapi.graphql -> services.heartbeat_service
  servers.flask.http -> services.heartbeat_service
  servers.flask.graphql -> services.heartbeat_service
  servers.litestar.http -> services.heartbeat_service
  servers.litestar.graphql -> services.heartbeat_service
  servers.starlette.http -> services.heartbeat_service
  servers.starlette.graphql -> services.heartbeat_service
  servers.grpc -> services.heartbeat_service

  services.quotes_service -> repository.peewee
  services.heartbeat_service -> repository.peewee
  services.quotes_service -> repository.sqlalchemy
  services.heartbeat_service -> repository.sqlalchemy
}

users -> app.servers.fastapi.http
users -> app.servers.fastapi.graphql
users -> app.servers.flask.http
users -> app.servers.flask.graphql
users -> app.servers.litestar.http
users -> app.servers.litestar.graphql
users -> app.servers.starlette.http
users -> app.servers.starlette.graphql
users -> app.servers.grpc

app.repository.peewee -> database
app.repository.sqlalchemy -> database

app.services.quotes_api_service -> random_quotes
